project:
  type: website

website:
  title: "Tan Gandhara"
  navbar:
    left: 
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: TidyTuesday 
        href: https://github.com/tangandhara/TidyTuesday
    right:
    - icon: linkedin
      href: https://www.linkedin.com/in/tan-gandhara
    - icon: twitter
      href: https://twitter.com/tangandhara
    - icon: github
      href: https://github.com/tangandhara
    - icon: envelope
      href: mailto:tangandhara+quarto@hotmail.com
format:
  html:
    theme: journal
    css: styles.css

editor: visual

